import { z } from 'zod';

import {
  createTRPCRouter,
  publicProcedure,
  // protectedProcedure
} from '../trpc';

import type { Product } from '../../../types/types';
import { filterProducts } from '../../../utils/filterProducts';

const demoProducts: Product[] = [
  {
    id: 1,
    image: '/products/1.png',
    title: 'Recycled Jeans',
    price: 200,
    views: 12_000,
    discount: 20,
    category: 'Bottoms',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colours: ['Black', 'Blue', 'Green', 'Grey'],
    rating: 4.5,
  },
  {
    id: 2,
    image: '/products/2.png',
    title: 'Organic Cotton Summer Wear',
    price: 610,
    views: 1_000,
    discount: 10,
    category: 'T-Shirts',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
    colours: ['Black', 'Blue', 'Green', 'Grey', 'Orange', 'Pink'],
    rating: 4.0,
  },
  {
    id: 3,
    image: '/products/3.png',
    title: 'Handcrafter Pure Cotton Coat',
    price: 290,
    views: 600,
    discount: 30,
    category: 'Outwear',
    material: 'Cotton',
    sizes: ['XS', 'S', 'XL', 'XXL'],
    colours: ['Black', 'Blue', 'Orange', 'Pink'],
    rating: 3.7,
  },
  {
    id: 4,
    image: '/products/4.png',
    title: 'Pure Cotton Char Coal Gray Sweatshirt',
    price: 599,
    views: 4_900,
    discount: 50,
    category: 'Sweat Shirts',
    material: 'Wool',
    sizes: ['M', 'L', 'XL', 'XXL'],
    colours: ['Black', 'Blue', 'Green', 'Grey', 'Orange', 'Pink'],
    rating: 4.1,
  },
  {
    id: 5,
    image: '/products/5.png',
    title: 'Linen Black Dress',
    price: 789,
    views: 6_200,
    discount: 20,
    category: 'Outwear',
    material: 'Linen',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colours: ['Black', 'Blue', 'Green', 'Grey'],
    rating: 4.1,
  },
  {
    id: 6,
    image: '/products/6.png',
    title: 'White Pure Cotton Shirt',
    price: 309,
    views: 1_008,
    discount: 10,
    category: 'Polos',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colours: ['Black', 'Blue', 'Green', 'Grey'],
    rating: 3.9,
  },
  {
    id: 7,
    image: '/products/7.png',
    title: 'Organic Cotton Cream Color Sweatshirt',
    price: 1_000,
    views: 8_800,
    discount: 20,
    category: 'Sweat Shirts',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colours: ['Black', 'Blue', 'Orange', 'Pink'],
    rating: 4.4,
  },
  {
    id: 8,
    image: '/products/8.png',
    title: 'Recycled Cotton Jeans',
    price: 599,
    views: 4_900,
    discount: 50,
    category: 'Bottoms',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colours: ['Black', 'Blue', 'Grey'],
    rating: 4.1,
  },
  {
    id: 9,
    image: '/products/9.png',
    title: 'Hemp Shirt And Paint',
    price: 200,
    views: 12_000,
    discount: 20,
    category: 'Polos',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colours: ['Black', 'Blue', 'Green', 'Grey'],
    rating: 4.5,
  },
  {
    id: 10,
    image: '/products/10.png',
    title: 'Organic Cotton Summer Wear',
    price: 610,
    views: 1_000,
    discount: 10,
    category: 'T-Shirts',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
    colours: ['Black', 'Blue', 'Green', 'Grey', 'Orange', 'Pink'],
    rating: 4.0,
  },
  {
    id: 11,
    image: '/products/11.png',
    title: 'Organic Cotton Summer Wear',
    price: 290,
    views: 600,
    discount: 30,
    category: 'T-Shirts',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
    colours: ['Black', 'Blue', 'Green', 'Grey', 'Orange', 'Pink'],
    rating: 3.7,
  },
  {
    id: 12,
    image: '/products/12.png',
    title: 'Bamboo Linen Tops Set Of 3',
    price: 599,
    views: 4_900,
    discount: 50,
    category: 'T-Shirts',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
    colours: ['Black', 'Blue', 'Green', 'Grey', 'Orange', 'Pink'],
    rating: 4.1,
  },
  {
    id: 13,
    image: '/products/10.png',
    title: 'Organic Cotton Pink Jacket',
    price: 610,
    views: 1_000,
    discount: 10,
    category: 'Jackets',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
    colours: ['Pink'],
    rating: 4.0,
  },
  {
    id: 14,
    image: '/products/11.png',
    title: 'Organic Cotton Summer Wear',
    price: 290,
    views: 600,
    discount: 30,
    category: 'T-Shirts',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
    colours: ['Black', 'Blue', 'Green', 'Grey', 'Orange', 'Pink'],
    rating: 3.7,
  },
  {
    id: 15,
    image: '/products/12.png',
    title: 'Bamboo Linen Tops Set Of 3',
    price: 599,
    views: 4_900,
    discount: 50,
    category: 'T-Shirts',
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L'],
    colours: ['Black', 'Blue', 'Green', 'Grey', 'Orange', 'Pink'],
    rating: 4.1,
  },
];

export const productRouter = createTRPCRouter({
  getAll: publicProcedure
    .input(
      z.object({
        page: z.number(),
        limit: z.number(),
        filters: z.object({
          category: z.array(z.string()),
          materials: z.array(z.string()),
          colours: z.array(z.string()),
          sizes: z.array(z.string()),
          discount: z.array(z.number()),
        }),
      })
    )
    .query(({ input: { page, limit, filters } }) => {
      const filteredProducts = filterProducts(demoProducts, filters);
      return {
        products: filteredProducts.slice((page - 1) * limit, page * limit),
        total: filteredProducts.length,
      };
    }),

  // getAll: publicProcedure.query(({ ctx }) => {
  //   return ctx.prisma.example.findMany();
  // }),

  // getSecretMessage: protectedProcedure.query(() => {
  //   return "you can now see this secret message!";
  // }),
});
